// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Demo is the predicate function for demo builders.
type Demo func(*sql.Selector)
