// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/suisrc/zgo/app/ent/demo"
)

// Demo is the model entity for the Demo schema.
type Demo struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Demo) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Demo fields.
func (d *Demo) assignValues(values ...interface{}) error {
	if m, n := len(values), len(demo.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	d.ID = int(value.Int64)
	values = values[1:]
	return nil
}

// Update returns a builder for updating this Demo.
// Note that, you need to call Demo.Unwrap() before calling this method, if this Demo
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Demo) Update() *DemoUpdateOne {
	return (&DemoClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (d *Demo) Unwrap() *Demo {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Demo is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Demo) String() string {
	var builder strings.Builder
	builder.WriteString("Demo(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Demos is a parsable slice of Demo.
type Demos []*Demo

func (d Demos) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
