basePath: /api
definitions:
  helper.ErrorInfo:
    properties:
      data:
        description: 响应数据
        type: object
      errorCode:
        description: 错误代码
        type: string
      errorMessage:
        description: 向用户显示消息
        type: string
      showType:
        description: 错误显示类型：0静音； 1条消息警告； 2消息错误； 4通知； 9页
        type: integer
      success:
        description: 请求成功, false
        type: boolean
      traceId:
        description: 方便进行后端故障排除：唯一的请求ID
        type: string
    type: object
  helper.Success:
    properties:
      data:
        description: 响应数据
        type: object
      success:
        description: 请求成功, false
        type: boolean
      traceId:
        description: 方便进行后端故障排除：唯一的请求ID
        type: string
    type: object
  schema.DemoSet:
    properties:
      code:
        description: 编号
        type: string
      memo:
        description: 备注
        type: string
      name:
        description: 名称
        type: string
    required:
    - code
    - name
    type: object
  schema.SigninBody:
    properties:
      captcha:
        description: 验证码
        type: string
      code:
        description: 登陆方式
        type: string
      mobile:
        description: 手机号
        type: string
      password:
        description: 密码
        type: string
      reset:
        description: 重置登陆
        type: boolean
      role:
        description: 角色
        type: string
      type:
        description: 登陆类型 <系统>:<类型>:<备注>
        type: string
      usrname:
        description: 账户
        type: string
    required:
    - usrname
    type: object
info:
  contact:
    email: susirc@outlook.com
    name: suisrc
  description: GIN + ENT/SQLX + CASBIN + WIRE
  license: {}
  title: zgo
  version: 0.0.1
paths:
  /authz:
    get:
      consumes:
      - application/json
      description: 授权接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      security:
      - ApiKeyAuth: []
      summary: Authorize
      tags:
      - auth
  /demo/get:
    get:
      consumes:
      - application/json
      description: Get
      parameters:
      - description: Demo id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ErrorInfo'
      summary: Get
      tags:
      - demo
  /demo/get1:
    get:
      consumes:
      - application/json
      description: Get
      parameters:
      - description: Demo id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ErrorInfo'
      summary: Get
      tags:
      - demo
  /demo/hello:
    get:
      consumes:
      - application/json
      description: Hello world
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Hello
      tags:
      - demo
  /demo/set:
    post:
      consumes:
      - application/json
      description: Set
      parameters:
      - description: Demo Info
        in: body
        name: item
        schema:
          $ref: '#/definitions/schema.DemoSet'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.ErrorInfo'
      summary: Set
      tags:
      - demo
  /signin:
    post:
      consumes:
      - application/json
      description: 登陆
      parameters:
      - description: SigninBody Info
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/schema.SigninBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: Signin
      tags:
      - sign
  /signout:
    get:
      consumes:
      - application/json
      description: 登出
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: Signin
      tags:
      - sign
  /user/hello:
    get:
      consumes:
      - application/json
      description: 用户接口测试
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helper.Success'
      summary: hello
      tags:
      - user
schemes:
- https
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
