// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/suisrc/zgo/demo/model/ent/demo"
	"github.com/suisrc/zgo/demo/model/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	demoFields := schema.Demo{}.Fields()
	_ = demoFields
	// demoDescStatus is the schema descriptor for status field.
	demoDescStatus := demoFields[3].Descriptor()
	// demo.DefaultStatus holds the default value on creation for the status field.
	demo.DefaultStatus = demoDescStatus.Default.(int)
	// demo.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	demo.StatusValidator = func() func(int) error {
		validators := demoDescStatus.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(status int) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// demoDescCreator is the schema descriptor for creator field.
	demoDescCreator := demoFields[4].Descriptor()
	// demo.DefaultCreator holds the default value on creation for the creator field.
	demo.DefaultCreator = demoDescCreator.Default.(string)
	// demoDescUpdator is the schema descriptor for updator field.
	demoDescUpdator := demoFields[5].Descriptor()
	// demo.DefaultUpdator holds the default value on creation for the updator field.
	demo.DefaultUpdator = demoDescUpdator.Default.(string)
	// demoDescCreatedAt is the schema descriptor for created_at field.
	demoDescCreatedAt := demoFields[6].Descriptor()
	// demo.DefaultCreatedAt holds the default value on creation for the created_at field.
	demo.DefaultCreatedAt = demoDescCreatedAt.Default.(func() time.Time)
	// demoDescUpdatedAt is the schema descriptor for updated_at field.
	demoDescUpdatedAt := demoFields[7].Descriptor()
	// demo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	demo.DefaultUpdatedAt = demoDescUpdatedAt.Default.(func() time.Time)
}
