// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DemoColumns holds the columns for the "demo" table.
	DemoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "memo", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt, Default: 1},
		{Name: "creator", Type: field.TypeString, Default: ""},
		{Name: "updator", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "demo_children", Type: field.TypeInt, Nullable: true},
	}
	// DemoTable holds the schema information for the "demo" table.
	DemoTable = &schema.Table{
		Name:       "demo",
		Columns:    DemoColumns,
		PrimaryKey: []*schema.Column{DemoColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "demo_demo_children",
				Columns: []*schema.Column{DemoColumns[9]},

				RefColumns: []*schema.Column{DemoColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DemoTable,
	}
)

func init() {
	DemoTable.ForeignKeys[0].RefTable = DemoTable
}
