// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"zgo/engine/gin"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	webFrameWork, err := gin.InitWebFrameWork()
	if err != nil {
		return nil, nil, err
	}
	injector := &Injector{
		EngineFunc: webFrameWork,
	}
	return injector, func() {
	}, nil
}
