// Code generated by entc, DO NOT EDIT.

package demo

const (
	// Label holds the string label denoting the demo type in the database.
	Label = "demo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the demo in the database.
	Table = "demos"
)

// Columns holds all SQL columns for demo fields.
var Columns = []string{
	FieldID,
}
