# 运行模式(debug:调试,test:测试,release:正式)
runmode = "debug"

# 是否启用swagger
swagger = false

# 启动时是否打印配置参数
printconfig = true

# 静态站点目录(也可以启动服务时使用-www指定)
[www]
index = "index.html"

[http]
# http监听地址
host = "0.0.0.0"
# http监听端口
port = 8080
# context
# ContextPath = "api/v1"
# 证书路径
certfile = ""
# 证书密钥
keyfile = ""
# http优雅关闭等待超时时长(单位秒)
shutdowntimeout = 30
# 允许的最大内容长度(64M)
maxcontentlength = 67108864
